name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: xip-online-applications/codeship-status-sync-action@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
